language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run unit
after_script:
  # - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
 - cat ./coverage/lcov.info | coveralls